# Generated by Django 3.2.25 on 2024-07-20 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiaNaoUtil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Militar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo_escala', models.CharField(choices=[('Oficial de Dia', 'Oficial de Dia'), ('Adjunto', 'Adjunto ao Oficial de Dia'), ('Comandante da Guarda', 'Comandante da Guarda'), ('Cabo da Guarda', 'Cabo da Guarda'), ('Cabo da Guarda do PNR', 'Cabo da Guarda do PNR')], max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('data_entrada', models.DateField()),
                ('folga_util', models.IntegerField(default=0)),
                ('folga_nao_util', models.IntegerField(default=0)),
                ('indisponibilidades', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServicoDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_escala', models.CharField(choices=[('Oficial de Dia', 'Oficial de Dia'), ('Adjunto', 'Adjunto ao Oficial de Dia'), ('Comandante da Guarda', 'Comandante da Guarda'), ('Cabo da Guarda', 'Cabo da Guarda'), ('Cabo da Guarda do PNR', 'Cabo da Guarda do PNR')], max_length=50)),
                ('data', models.DateField()),
                ('status', models.BooleanField(default=True)),
                ('tipo_dia', models.CharField(choices=[('util', 'Útil'), ('nao_util', 'Não Útil')], max_length=10)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('militar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.militar')),
            ],
        ),
    ]
