# Generated by Django 3.2.25 on 2024-07-20 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Militar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('posto', models.CharField(max_length=50)),
                ('data_entrada', models.DateField()),
                ('suspenso_ate', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('tipo', models.CharField(choices=[('preta', 'Preta'), ('vermelha', 'Vermelha')], max_length=8)),
                ('funcao', models.CharField(choices=[('OFICIAL_DIA', 'Oficial de Dia'), ('ADJUNTO_OF_DIA', 'Adjunto ao Oficial de Dia'), ('COMANDANTE_GUARDA', 'Comandante da Guarda'), ('CABO_GUARDA', 'Cabo da Guarda'), ('CABO_GUARDA_PNR', 'Cabo da Guarda do PNR')], max_length=20)),
                ('militar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.militar')),
            ],
        ),
    ]
