# Generated by Django 3.2.25 on 2024-07-20 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20240720_2354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicodiario',
            old_name='folga_nao_util',
            new_name='folga',
        ),
        migrations.RemoveField(
            model_name='servicodiario',
            name='folga_util',
        ),
    ]
