# Generated by Django 3.2.25 on 2024-07-21 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20240720_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolgaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('folga', models.IntegerField()),
                ('tipo_dia', models.CharField(max_length=10)),
                ('militar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.militar')),
            ],
        ),
    ]
